//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPPPDFFindReplace
#define PDFTRON_H_CPPPDFFindReplace
#include <C/PDF/TRN_FindReplace.h>

#include <Common/BasicTypes.h>
#include <Common/UString.h>
#include <PDF/PDFDoc.h>
#include <PDF/FindReplaceOptions.h>

namespace pdftron { namespace PDF { 


/**
 * The class FindReplace.
 * static interface to Iceni Find/Replace text functionality
 */
class FindReplace
{
public:

	/**
	 * Finds and Replaces text within a PDF.
	 *
	 * @param input_output_pdf The pdf to be processed.
	 * @param from Text to find in the PDF.
	 * @param to Text to replace with in the PDF.
	 * @param options FindReplace options (optional).
	 */
	static void FindReplaceText(PDFDoc& input_output_pdf, const UString& from, const UString& to, const FindReplaceOptions& options = FindReplaceOptions());

};

#include <Impl/FindReplace.inl>
} //end pdftron
} //end PDF


#endif //PDFTRON_H_CPPPDFFindReplace
