//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPPPDFSanitizer
#define PDFTRON_H_CPPPDFSanitizer
#include <C/PDF/TRN_Sanitizer.h>

#include <PDF/PDFDoc.h>
#include <PDF/SanitizeOptions.h>

namespace pdftron { namespace PDF { 
class SanitizeOptions;

/**
 * The class Sanitizer.
 * static interface to Apryse SDKs document sanitization functionality
 */
class Sanitizer
{
public:
		
	/**
	 * Retrieves the types of sanitizable content that are present within the
	 * document.
	 * 
	 * @param doc The document to inspect for sanitizable content.
	 * @return Returns the sanitization options with all sanitizable content present
	 * within the document enabled.
	 */
	static SanitizeOptions GetSanitizableContent(PDFDoc& doc);
	
	/**
	 * Performs document sanitization based on the specified sanitize
	 * options. If no options are provided, all sanitizable content present
	 * will be removed.
	 * 
	 * @param doc The document to sanitize.
	 * @param options Document sanitization options (optional).
	 */
	static void SanitizeDocument(PDFDoc& doc, const SanitizeOptions* options);

};

#include <Impl/Sanitizer.inl>
} //end pdftron
} //end PDF


#endif //PDFTRON_H_CPPPDFSanitizer
