//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPPPDFStructuredOutputModule
#define PDFTRON_H_CPPPDFStructuredOutputModule
#include <C/PDF/TRN_StructuredOutputModule.h>

#include <Common/BasicTypes.h>
#include <Common/UString.h>
#include <PDF/PDFDoc.h>

namespace pdftron { namespace PDF { 
class PDFDoc;

/**
 * The class StructuredOutputModule.
 * static interface to PDFTron SDKs PDF to Word, Excel, PowerPoint, HTML functionality
 */
class StructuredOutputModule
{
public:
	
	//methods:
	
	/**
	 * Find out whether the StructuredOutput add-on module is available (and licensed).
	 * 
	 * @return returns true if StructuredOutput operations can be performed.
	 */
	static bool IsModuleAvailable();

};

#include <Impl/StructuredOutputModule.inl>
} //end pdftron
} //end PDF


#endif //PDFTRON_H_CPPPDFStructuredOutputModule
