//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CList
#define PDFTRON_H_CList

#ifdef __cplusplus 
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>

	enum TRN_ListNumberFormat
	{
		e_List_none = 0,
		e_List_decimal,
		e_List_lower_roman,
		e_List_upper_roman,
		e_List_lower_letter,
		e_List_upper_letter,
		e_List_ordinal,
		e_List_ordinal_text,
		e_List_chinese_counting,
		e_List_chinese_counting_thousand,
		e_List_cardinal_text,
		e_List_decimal_zero,
	};

	TRN_API TRN_ListAsContentElement(TRN_List self, TRN_ContentElement* result);

	TRN_API TRN_ListSetNumberFormat(TRN_List self, TRN_ListNumberFormat format, TRN_UString suffix, TRN_Bool cascade);
	TRN_API TRN_ListSetStartIndex(TRN_List self, int idx);

	TRN_API TRN_ListAddItem(TRN_List self, TRN_ListItem* result);

	TRN_API TRN_ListGetIndentationLevel(TRN_List self, int* result);
	TRN_API TRN_ListGetListIdentifier(TRN_List self, int* result);

	TRN_API TRN_ListContinueList(TRN_List self);

	TRN_API TRN_ListGetContentNodeIterator(TRN_List self, TRN_Iterator* result);
	TRN_API TRN_ListGetTextStyledElement(TRN_List self, TRN_TextStyledElement* result);

#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CList */
