//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CListItem
#define PDFTRON_H_CListItem

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>

	TRN_API TRN_ListItemAsContentElement(TRN_ListItem self, TRN_ContentElement* result);
	TRN_API TRN_ListItemAddParagraph(TRN_ListItem self, TRN_Paragraph* result);
	TRN_API TRN_ListItemAddParagraphWithText(TRN_ListItem self, TRN_UString text, TRN_Paragraph* result);
	TRN_API TRN_ListItemAddList(TRN_ListItem self, TRN_List* result);
	TRN_API TRN_ListItemGetIndentationLevel(TRN_ListItem self, int* result);
	TRN_API TRN_ListItemGetListIdentifier(TRN_ListItem self, int* result);
	TRN_API TRN_ListItemGetItemIndex(TRN_ListItem self, int* result);
	TRN_API TRN_ListItemGetContentNodeIterator(TRN_ListItem self, TRN_Iterator* result);
	TRN_API TRN_ListItemGetTextStyledElement(TRN_ListItem self, TRN_TextStyledElement* result);

#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CListItem */ 
