//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CTableCell
#define PDFTRON_H_CTableCell


#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>
	
enum TRN_TableCellAlignmentVertical
{
	e_TableCell_alignment_vert_invalid = 0,
	e_TableCell_alignment_top = 1,
	e_TableCell_alignment_center = 2,
	e_TableCell_alignment_bottom = 3
};

enum TRN_TableCellAlignmentHorizontal
{
	e_TableCell_alignment_horz_invalid = 0,
	e_TableCell_alignment_left = 1,
	e_TableCell_alignment_middle = 2,
	e_TableCell_alignment_right = 3,
};


TRN_API TRN_TableCellAddParagraph(TRN_TableCell self, TRN_Paragraph* result);
TRN_API TRN_TableCellAddParagraphWithText(TRN_TableCell self, const TRN_UString text, TRN_Paragraph* result);
TRN_API TRN_TableCellAddTable(TRN_TableCell self, TRN_Table* result);

TRN_API TRN_TableCellMergeCellsRight(TRN_TableCell self, TRN_UInt32 num, TRN_TableCell* result);
TRN_API TRN_TableCellMergeCellsDown(TRN_TableCell self, TRN_UInt32 num, TRN_TableCell* result);

TRN_API TRN_TableCellSetBackgroundColor(TRN_TableCell self, TRN_UInt8 red,  TRN_UInt8 green, TRN_UInt8 blue);

TRN_API TRN_TableCellSetBorder(TRN_TableCell self, double thickness, TRN_UInt8 red,  TRN_UInt8 green, TRN_UInt8 blue);
TRN_API TRN_TableCellGetBorderThickness(TRN_TableCell self, double* result);

TRN_API TRN_TableCellSetVerticalAlignment(TRN_TableCell self, enum TRN_TableCellAlignmentVertical val);
TRN_API TRN_TableCellGetVerticalAlignment(TRN_TableCell self, TRN_TableCellAlignmentVertical* result);

TRN_API TRN_TableCellSetHorizontalAlignment(TRN_TableCell self, enum TRN_TableCellAlignmentHorizontal val);
TRN_API TRN_TableCellGetHorizontalAlignment(TRN_TableCell self, TRN_TableCellAlignmentHorizontal* result);

TRN_API TRN_TableCellSetHeight(TRN_TableCell self, double val);
TRN_API TRN_TableCellGetHeight(TRN_TableCell self, double* result);
TRN_API TRN_TableCellSetWidth(TRN_TableCell self, double val);
TRN_API TRN_TableCellGetWidth(TRN_TableCell self, double* result);

#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CTableCell */
