//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CBarcodeModule
#define PDFTRON_H_CBarcodeModule

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_BarcodeModule_tag;
typedef struct TRN_BarcodeModule_tag* TRN_BarcodeModule;

TRN_API TRN_BarcodeModuleIsModuleAvailable(TRN_Bool* result);
TRN_API TRN_BarcodeModuleExtractBarcodes(TRN_PDFDoc src, TRN_UString output_file_path, const TRN_OptionBase* options);
TRN_API TRN_BarcodeModuleExtractBarcodesAsString(TRN_PDFDoc src, const TRN_OptionBase* options, TRN_UString* result);
TRN_API TRN_BarcodeModuleExtractBarcodesWithOptsObj(TRN_PDFDoc src, TRN_UString output_file_path, TRN_Obj options);
TRN_API TRN_BarcodeModuleExtractBarcodesAsStringWithOptsObj(TRN_PDFDoc src, TRN_Obj options, TRN_UString* result);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CBarcodeModule */
