//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CReflow
#define PDFTRON_H_CReflow

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_Reflow_tag;
typedef struct TRN_Reflow_tag* TRN_Reflow;


/* methods: */
TRN_API TRN_ReflowGetHtml(TRN_Reflow self, TRN_UString* result);
TRN_API TRN_ReflowGetAnnot(TRN_Reflow self, TRN_UString in_id, TRN_UString* result);
TRN_API TRN_ReflowSetAnnot(TRN_Reflow self, TRN_UString in_json, TRN_UString* result);
TRN_API TRN_ReflowSetIncludeImages(TRN_Reflow self, TRN_Bool include);
TRN_API TRN_ReflowSetHTMLOutputTextMarkup(TRN_Reflow self, TRN_Bool include);
TRN_API TRN_ReflowSetMessageWhenNoReflowContent(TRN_Reflow self, TRN_UString content);
TRN_API TRN_ReflowSetMessageWhenReflowFailed(TRN_Reflow self, TRN_UString content);
TRN_API TRN_ReflowSetHideBackgroundImages(TRN_Reflow self, TRN_Bool hide_background_images);
TRN_API TRN_ReflowSetHideImagesUnderText(TRN_Reflow self, TRN_Bool hide_images_under_text);
TRN_API TRN_ReflowSetHideImagesUnderInvisibleText(TRN_Reflow self, TRN_Bool hide_images_under_invisible_text);
TRN_API TRN_ReflowSetDoNotReflowTextOverImages(TRN_Reflow self, TRN_Bool do_not_reflow_text_over_images);
TRN_API TRN_ReflowSetFontOverrideName(TRN_Reflow self, TRN_UString font_family);
TRN_API TRN_ReflowSetCustomStyles(TRN_Reflow self, TRN_UString styles);
TRN_API TRN_ReflowSetIncludeBBoxForRecognizedZones(TRN_Reflow self, TRN_Bool include);

TRN_API TRN_ReflowDestroy(TRN_Reflow self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CReflow */
