//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CSanitizer
#define PDFTRON_H_CSanitizer

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_Sanitizer_tag;
typedef struct TRN_Sanitizer_tag* TRN_Sanitizer;


TRN_API TRN_SanitizerGetSanitizableContent(TRN_PDFDoc doc, TRN_UString* result);
TRN_API TRN_SanitizerSanitizeDocument(TRN_PDFDoc doc, const TRN_OptionBase* options);
TRN_API TRN_SanitizerSanitizeDocumentWithOptsObj(TRN_PDFDoc doc, TRN_Obj options);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CSanitizer */
