//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPPHandwritingICRModule
#define PDFTRON_H_CPPHandwritingICRModule
#include <C/PDF/TRN_HandwritingICRModule.h>

#include <Common/BasicTypes.h>
#include <Common/UString.h>
#include <PDF/PDFDoc.h>
#include <PDF/HandwritingICROptions.h>

namespace pdftron { namespace PDF { 


/**
 * The class HandwritingICRModule.
 * static interface to Apryse SDK's handwriting extraction functionality
 */
class HandwritingICRModule
{
public:
		
	/**
	 * Find out whether the Handwriting ICR Module is available (and
	 * licensed).
	 * 
	 * @return Returns true if handwriting extraction can be performed.
	 */
	static bool IsModuleAvailable();
	
	/**
	 * Perform handwriting extraction on a PDF and return a JSON object of
	 * detected handwriting as a string.
	 * 
	 * @param src The source document.
	 * @param options Handwriting ICR options (optional).
	 * @return JSON string representing handwriting extraction results.
	 */
	static UString GetICRJsonFromPDF(PDFDoc& src, const HandwritingICROptions* options = 0);

	/**
	 * Add a searchable and selectable hidden text layer to a PDF consisting of raster image(s)
	 * based on handwriting extraction performed in a previous function call.
	 * 
	 * @param dst The source and destination document.
	 * @param json JSON representing ICR results.
	 */
	static void ApplyICRJsonToPDF(PDFDoc& dst, const UString& json);

	/**
	 * Perform handwriting extraction and add searchable and selectable text to a PDF.
	 * 
	 * @param dst The source and destination document.
	 * @param options Handwriting ICR options (optional).
	 */
	static void ProcessPDF(PDFDoc& dst, const HandwritingICROptions* options = 0);
	
};

#include <Impl/HandwritingICRModule.inl>
} //end pdftron
} //end PDF


#endif //PDFTRON_H_CPPPDFHandwritingICRModule
