// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFHandwritingICROptions
#define PDFTRON_H_CPPPDFHandwritingICROptions

#include <PDF/OptionsBase.h>

namespace pdftron{ namespace PDF{ 

class HandwritingICROptions : public OptionsBase
{
public:
	HandwritingICROptions();
	~HandwritingICROptions();

	
	/**
	* Adds the value to the IgnoreZonesForPage array.
	* Optional list of page areas to be excluded from analysis. Zones should
	* be provided as a collection of Rects paired with a page number. The
	* Rects are then applied to the corresponding page. Rects are specified
	* in User Space coordinates. If this is set, the specified areas will
	* not be analyzed. If neither this nor InclusionZonesForPage is set,
	* the entire page will be analyzed.
	* @param value List of page areas to be excluded from analysis.
	* @param page_num The page number (1-indexed) to which the regions are applied.
	* @return This object, for call chaining.
	*/
	HandwritingICROptions& AddIgnoreZonesForPage(const RectCollection& value, int page_num);

	
	/**
	* Adds the value to the InclusionZonesForPage array.
	* Optional list of page areas to be included in analysis (to the
	* exclusion of all other areas). Zones should be provided as a
	* collection of Rects paired with a page number. The Rects are then
	* applied to the corresponding page. Rects are specified in User Space
	* coordinates. If this is set, only the areas specified will be
	* analyzed. If neither this nor IgnoreZonesForPage is set, the entire
	* page will be analyzed.
	* @param value List of page areas to be included in analysis.
	* @param page_num The page number (1-indexed) to which the regions are applied.
	* @return This object, for call chaining.
	*/
	HandwritingICROptions& AddInclusionZonesForPage(const RectCollection& value, int page_num);

	
	/**
	* Gets the value Pages from the options object.
	* Specifies a range of pages on which to perform handwriting extraction,
	* such as "1-5". Open-ended ranges are supported, e.g.,
	* "3-". By default all pages are converted. The first page is page
	* number 1.
	* @return The current value for Pages.
	*/
	UString GetPages();

	/**
	* Sets the value for Pages in the options object.
	* Specifies a range of pages on which to perform handwriting extraction,
	* such as "1-5". Open-ended ranges are supported, e.g.,
	* "3-". By default all pages are converted. The first page is page
	* number 1.
	* @param value The new value for Pages.
	* @return This object, for call chaining.
	*/
	HandwritingICROptions& SetPages(const UString& value);

	
};

}
}

#include "../Impl/HandwritingICROptions.inl"
#endif // PDFTRON_H_CPPPDFHandwritingICROptions
