// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFSanitizeOptions
#define PDFTRON_H_CPPPDFSanitizeOptions

#include <PDF/OptionsBase.h>

namespace pdftron{ namespace PDF{ 

class SanitizeOptions : public OptionsBase
{
public:
	SanitizeOptions();
	SanitizeOptions(const UString& json);
	~SanitizeOptions();

	
	/**
	* Gets the value Actions from the options object.
	* Remove any actions such as scripts and links present in the document.
	* By default this option is set to false.
	* @return The current value for Actions.
	*/
	bool GetActions();

	/**
	* Sets the value for Actions in the options object.
	* Remove any actions such as scripts and links present in the document.
	* By default this option is set to false.
	* @param value The new value for Actions.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetActions(bool value);

	
	/**
	* Gets the value Bookmarks from the options object.
	* Remove any bookmarks present in the document. By default this option
	* is set to false.
	* @return The current value for Bookmarks.
	*/
	bool GetBookmarks();

	/**
	* Sets the value for Bookmarks in the options object.
	* Remove any bookmarks present in the document. By default this option
	* is set to false.
	* @param value The new value for Bookmarks.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetBookmarks(bool value);

	
	/**
	* Gets the value EmbeddedContent from the options object.
	* Remove any embedded content, such as attached files present in the
	* document. By default this option is set to false.
	* @return The current value for EmbeddedContent.
	*/
	bool GetEmbeddedContent();

	/**
	* Sets the value for EmbeddedContent in the options object.
	* Remove any embedded content, such as attached files present in the
	* document. By default this option is set to false.
	* @param value The new value for EmbeddedContent.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetEmbeddedContent(bool value);

	
	/**
	* Gets the value FormData from the options object.
	* Flatten any form data present in the document. By default this option
	* is set to false.
	* @return The current value for FormData.
	*/
	bool GetFormData();

	/**
	* Sets the value for FormData in the options object.
	* Flatten any form data present in the document. By default this option
	* is set to false.
	* @param value The new value for FormData.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetFormData(bool value);


	/**
	* Gets the value HiddenLayers from the options object.
	* Remove any hidden layers present in the document. By default this
	* option is set to false.
	* @return The current value for HiddenLayers.
	*/
	bool GetHiddenLayers();

	/**
	* Sets the value for HiddenLayers in the options object.
	* Remove any hidden layers present in the document. By default this
	* option is set to false.
	* @param value The new value for HiddenLayers.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetHiddenLayers(bool value);

	
	/**
	* Gets the value HiddenText from the options object.
	* Remove any hidden text present in the document. By default this option
	* is set to false.
	* @return The current value for HiddenText.
	*/
	bool GetHiddenText();

	/**
	* Sets the value for HiddenText in the options object.
	* Remove any hidden text present in the document. By default this option
	* is set to false.
	* @param value The new value for HiddenText.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetHiddenText(bool value);

	
	/**
	* Gets the value Markups from the options object.
	* Remove any markups and associated comments present in the document. By
	* default this option is set to false.
	* @return The current value for Markups.
	*/
	bool GetMarkups();

	/**
	* Sets the value for Markups in the options object.
	* Remove any markups and associated comments present in the document. By
	* default this option is set to false.
	* @param value The new value for Markups.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetMarkups(bool value);

	
	/**
	* Gets the value Metadata from the options object.
	* Remove any metadata present in the document. By default this option is
	* set to false.
	* @return The current value for Metadata.
	*/
	bool GetMetadata();

	/**
	* Sets the value for Metadata in the options object.
	* Remove any metadata present in the document. By default this option is
	* set to false.
	* @param value The new value for Metadata.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetMetadata(bool value);

	
	/**
	* Gets the value OccludedText from the options object.
	* Remove any text that is occluded within the document (such as clipped
	* by the cropbox or another element). By default this option is set to
	* false.
	* @return The current value for OccludedText.
	*/
	bool GetOccludedText();

	/**
	* Sets the value for OccludedText in the options object.
	* Remove any text that is occluded within the document (such as clipped
	* by the cropbox or another element). By default this option is set to
	* false.
	* @param value The new value for OccludedText.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetOccludedText(bool value);

	
	/**
	* Gets the value SearchIndices from the options object.
	* Remove any embedded search indices present in the document. By Default
	* this option is set to false.
	* @return The current value for SearchIndices.
	*/
	bool GetSearchIndices();

	/**
	* Sets the value for SearchIndices in the options object.
	* Remove any embedded search indices present in the document. By Default
	* this option is set to false.
	* @param value The new value for SearchIndices.
	* @return This object, for call chaining.
	*/
	SanitizeOptions& SetSearchIndices(bool value);

	
};

}
}

#include "../Impl/SanitizeOptions.inl"
#endif // PDFTRON_H_CPPPDFSanitizeOptions
