// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFTaggingOptions
#define PDFTRON_H_CPPPDFTaggingOptions

#include <PDF/OptionsBase.h>

namespace pdftron{ namespace PDF{ 

class TaggingOptions : public OptionsBase
{
public:
	TaggingOptions();
	~TaggingOptions();

	
	/**
	* Gets the value Description from the options object.
	* Alternate description required by some standards. Default is empty,
	* which will automatically attempt to fill it using contextual
	* information (such as TU for Widgets), but explicitly setting this is
	* recommended for better semantics.
	* @return The current value for Description.
	*/
	UString GetDescription();

	/**
	* Sets the value for Description in the options object.
	* Alternate description required by some standards. Default is empty,
	* which will automatically attempt to fill it using contextual
	* information (such as TU for Widgets), but explicitly setting this is
	* recommended for better semantics.
	* @param value The new value for Description.
	* @return This object, for call chaining.
	*/
	TaggingOptions& SetDescription(const UString& value);

	
	/**
	* Gets the value InsertIndex from the options object.
	* The index, in the parent SElement's kids array, at which to insert the
	* new tag. The new element will be inserted before the element at the
	* insert index, where the first element is at index 0. If insert index
	* >= number of elements, it will be inserted at the end. Default inserts
	* at the end.
	* @return The current value for InsertIndex.
	*/
	UInt32 GetInsertIndex();

	/**
	* Sets the value for InsertIndex in the options object.
	* The index, in the parent SElement's kids array, at which to insert the
	* new tag. The new element will be inserted before the element at the
	* insert index, where the first element is at index 0. If insert index
	* >= number of elements, it will be inserted at the end. Default inserts
	* at the end.
	* @param value The new value for InsertIndex.
	* @return This object, for call chaining.
	*/
	TaggingOptions& SetInsertIndex(UInt32 value);

	
};

}
}

#include "../Impl/TaggingOptions.inl"
#endif // PDFTRON_H_CPPPDFTaggingOptions
