// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ namespace PDFUA{ 

inline PDFUAOptions::PDFUAOptions()
	: OptionsBase()
{
}

inline PDFUAOptions::~PDFUAOptions()
{
}


inline PDFUAConformance::Level PDFUAOptions::GetConformanceLevel()
{
	SDF::Obj found = m_dict.FindObj("Conformance");
	if(found.IsValid())
	{
		return (PDFUAConformance::Level)(int)(found.GetNumber());
	}
	return (PDFUAConformance::Level)(int)(PDFUAConformance::e_UA_Level1);
}

inline PDFUAOptions& PDFUAOptions::SetConformanceLevel(PDFUAConformance::Level value)
{
	PDF::OptionsBase::PutNumber(m_dict, "Conformance", (value));
	return *this;
}


inline UString PDFUAOptions::GetDefaultLangCode()
{
	SDF::Obj found = m_dict.FindObj("DefaultLangCode");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline PDFUAOptions& PDFUAOptions::SetDefaultLangCode(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "DefaultLangCode", (value));
	return *this;
}


inline UString PDFUAOptions::GetFigureAltTextPrefix()
{
	SDF::Obj found = m_dict.FindObj("FigureAltTextPrefix");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline PDFUAOptions& PDFUAOptions::SetFigureAltTextPrefix(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "FigureAltTextPrefix", (value));
	return *this;
}


inline bool PDFUAOptions::GetFirstStop()
{
	SDF::Obj found = m_dict.FindObj("FirstStop");
	if(found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline PDFUAOptions& PDFUAOptions::SetFirstStop(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "FirstStop", (value));
	return *this;
}


inline UInt32 PDFUAOptions::GetMaxRefObjs()
{
	SDF::Obj found = m_dict.FindObj("MaxRefObjs");
	if(found.IsValid())
	{
		return (UInt32)(found.GetNumber());
	}
	return (UInt32)(10);
}

inline PDFUAOptions& PDFUAOptions::SetMaxRefObjs(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "MaxRefObjs", (value));
	return *this;
}


inline UString PDFUAOptions::GetPassword()
{
	SDF::Obj found = m_dict.FindObj("Password");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline PDFUAOptions& PDFUAOptions::SetPassword(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Password", (value));
	return *this;
}


inline bool PDFUAOptions::GetSaveLinearized()
{
	SDF::Obj found = m_dict.FindObj("SaveLinearized");
	if(found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline PDFUAOptions& PDFUAOptions::SetSaveLinearized(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "SaveLinearized", (value));
	return *this;
}


}
}
}
