//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CTransPDF
#define PDFTRON_H_CTransPDF

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_TransPDF_tag;
typedef struct TRN_TransPDF_tag* TRN_TransPDF;

TRN_API TRN_TransPDFExtractXLIFFWithFilter(TRN_PDFDoc input_output_pdf, TRN_Filter output_stream_for_xliff, const TRN_OptionBase* options);
TRN_API TRN_TransPDFApplyXLIFFWithFilter(TRN_PDFDoc input, TRN_Filter incoming_xliff, const TRN_OptionBase* options);
TRN_API TRN_TransPDFExtractXLIFF(TRN_PDFDoc input_output_pdf, TRN_UString output_xliff, const TRN_OptionBase* options);
TRN_API TRN_TransPDFApplyXLIFF(TRN_PDFDoc input, TRN_UString incoming_xliff, const TRN_OptionBase* options);

TRN_API TRN_TransPDFExtractXLIFFWithFilterWithOptsObj(TRN_PDFDoc input_output_pdf, TRN_Filter output_stream_for_xliff, TRN_Obj options);
TRN_API TRN_TransPDFApplyXLIFFWithFilterWithOptsObj(TRN_PDFDoc input, TRN_Filter incoming_xliff, TRN_Obj options);
TRN_API TRN_TransPDFExtractXLIFFWithOptsObj(TRN_PDFDoc input_output_pdf, TRN_UString output_xliff, TRN_Obj options);
TRN_API TRN_TransPDFApplyXLIFFWithOptsObj(TRN_PDFDoc input, TRN_UString incoming_xliff, TRN_Obj options);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CTransPDF */
