//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CFindReplace
#define PDFTRON_H_CFindReplace

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_FindReplace_tag;
typedef struct TRN_FindReplace_tag* TRN_FindReplace;

TRN_API TRN_FindReplaceFindReplaceText(TRN_PDFDoc input, TRN_UString from, TRN_UString to, const TRN_OptionBase* options);


TRN_API TRN_FindReplaceFindReplaceTextWithOptsObj(TRN_PDFDoc input, TRN_UString from, TRN_UString to, TRN_Obj options);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CFindReplace */
