//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPDFUAConformance
#define PDFTRON_H_CPDFUAConformance

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_PDFUAConformance_tag;
typedef struct TRN_PDFUAConformance_tag* TRN_PDFUAConformance;

enum TRN_PDFUAConformance_Level
{
	e_PDFUAConformance_UA_Level1 = 0 
};
TRN_API TRN_PDFUAConformanceCreate(TRN_PDFUAConformance* result);

TRN_API TRN_PDFUAConformanceAutoConvert(TRN_PDFUAConformance self, TRN_UString src_file, TRN_UString dest_file, const TRN_OptionBase* in_options);

TRN_API TRN_PDFUAConformanceDestroy(TRN_PDFUAConformance self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CPDFUAConformance */
