//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CTable
#define PDFTRON_H_CTable


#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>
	
TRN_API TRN_TableAddTableRow(TRN_Table self, TRN_TableRow* result);
TRN_API TRN_TableGetTableCell(TRN_Table self, TRN_UInt32 column,  TRN_UInt32 row, TRN_TableCell* result);

TRN_API TRN_TableSetDefaultColumnWidth(TRN_Table self, double val);

TRN_API TRN_TableGetDefaultRowHeight(TRN_Table self, double* result);
TRN_API TRN_TableSetDefaultRowHeight(TRN_Table self, double val);

TRN_API TRN_TableGetNumRows(TRN_Table self, TRN_UInt32* result);
TRN_API TRN_TableGetNumColumns(TRN_Table self, TRN_UInt32* result);

TRN_API TRN_TableSetBorder(TRN_Table self, double thickness, TRN_UInt8 red, TRN_UInt8 green, TRN_UInt8 blue);
TRN_API TRN_TableGetBorderThickness(TRN_Table self, double* result);

#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CParagraph */
