// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline MergeXFDFOptions::MergeXFDFOptions()
	: OptionsBase()
{
}

inline MergeXFDFOptions::~MergeXFDFOptions()
{
}


inline bool MergeXFDFOptions::GetForce()
{
	SDF::Obj found = m_dict.FindObj("Force");
	if(found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline MergeXFDFOptions& MergeXFDFOptions::SetForce(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "Force", (value));
	return *this;
}


inline bool MergeXFDFOptions::GetUseNonStandardRotation()
{
	SDF::Obj found = m_dict.FindObj("UseNonStandardRotation");
	if(found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline MergeXFDFOptions& MergeXFDFOptions::SetUseNonStandardRotation(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "UseNonStandardRotation", (value));
	return *this;
}


}
}
