// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline TaggingOptions::TaggingOptions()
	: OptionsBase()
{
}

inline TaggingOptions::~TaggingOptions()
{
}


inline UString TaggingOptions::GetDescription()
{
	SDF::Obj found = m_dict.FindObj("Description");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline TaggingOptions& TaggingOptions::SetDescription(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Description", (value));
	return *this;
}


inline UInt32 TaggingOptions::GetInsertIndex()
{
	SDF::Obj found = m_dict.FindObj("InsertIndex");
	if(found.IsValid())
	{
		return (UInt32)(found.GetNumber());
	}
	return (UInt32)(-1);
}

inline TaggingOptions& TaggingOptions::SetInsertIndex(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "InsertIndex", (value));
	return *this;
}


}
}
