// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline TransPDFOptions::TransPDFOptions()
	: OptionsBase()
{
}

inline TransPDFOptions::~TransPDFOptions()
{
}


inline UInt32 TransPDFOptions::GetBatchSize()
{
	SDF::Obj found = m_dict.FindObj("BatchSize");
	if(found.IsValid())
	{
		return (UInt32)(found.GetNumber());
	}
	return (UInt32)(20);
}

inline TransPDFOptions& TransPDFOptions::SetBatchSize(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "BatchSize", (value));
	return *this;
}


inline UString TransPDFOptions::GetPages()
{
	SDF::Obj found = m_dict.FindObj("Pages");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline TransPDFOptions& TransPDFOptions::SetPages(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Pages", (value));
	return *this;
}


inline bool TransPDFOptions::GetResizeSingleLine()
{
	SDF::Obj found = m_dict.FindObj("ResizeSingleLine");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline TransPDFOptions& TransPDFOptions::SetResizeSingleLine(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "ResizeSingleLine", (value));
	return *this;
}


inline bool TransPDFOptions::GetFlipPageContentsForBiDirectionalTranslations()
{
	SDF::Obj found = m_dict.FindObj("FlipPageContentsForBiDirectionalTranslations");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline TransPDFOptions& TransPDFOptions::SetFlipPageContentsForBiDirectionalTranslations(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "FlipPageContentsForBiDirectionalTranslations", (value));
	return *this;
}


inline UString TransPDFOptions::GetSourceLanguage()
{
	SDF::Obj found = m_dict.FindObj("SourceLanguage");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("en");
}

inline TransPDFOptions& TransPDFOptions::SetSourceLanguage(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "SourceLanguage", (value));
	return *this;
}


inline TransPDFOptions::XLIFFVersion TransPDFOptions::GetXLIFFVersion()
{
	SDF::Obj found = m_dict.FindObj("XLIFFVersion");
	if (found.IsValid())
	{
		return (XLIFFVersion)(int)(found.GetNumber());
	}
	return (XLIFFVersion)(int)(1);
}

inline TransPDFOptions& TransPDFOptions::SetXLIFFVersion(TransPDFOptions::XLIFFVersion value)
{
	PDF::OptionsBase::PutNumber(m_dict, "XLIFFVersion", (value));
	return *this;
}


}
}
