// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFMergeXFDFOptions
#define PDFTRON_H_CPPPDFMergeXFDFOptions

#include <PDF/OptionsBase.h>

namespace pdftron{ namespace PDF{ 

class MergeXFDFOptions : public OptionsBase
{
public:
	MergeXFDFOptions();
	~MergeXFDFOptions();

	
	/**
	* Gets the value Force from the options object.
	* If true, merge will be performed even if the conditions below are true. If false, the MergeXFDF operation will be aborted with exception if one of these conditions is true: 1)xfdf contains annotations with no 'name' attribute 2)annotations in pdf or xfdf have names that are not unique, i.e. multiple annotations in the same document have the same name. In order for the merge operation to work correctly, all the annotations in xfdf need to have a unique 'name' attribute. If pdf document has unnamed annotatations (no 'NM' attribute), xfdf files generated using Apryse SDK will still have names that will allow the MergeXFDF algorithm to work.
	* @return The current value for Force.
	*/
	bool GetForce();

	/**
	* Sets the value for Force in the options object.
	* If true, merge will be performed even if the conditions below are true. If false, the MergeXFDF operation will be aborted with exception if one of these conditions is true: 1)xfdf contains annotations with no 'name' attribute 2)annotations in pdf or xfdf have names that are not unique, i.e. multiple annotations in the same document have the same name. In order for the merge operation to work correctly, all the annotations in xfdf need to have a unique 'name' attribute. If pdf document has unnamed annotatations (no 'NM' attribute), xfdf files generated using Apryse SDK will still have names that will allow the MergeXFDF algorithm to work.
	* @param value The new value for Force.
	* @return This object, for call chaining.
	*/
	MergeXFDFOptions& SetForce(bool value);

	
	/**
	* Gets the value UseNonStandardRotation from the options object.
	* Whether we should use rotation in the annotation even if it is not a multiple of 90. Off by default.
	* @return The current value for UseNonStandardRotation.
	*/
	bool GetUseNonStandardRotation();

	/**
	* Sets the value for UseNonStandardRotation in the options object.
	* Whether we should use rotation in the annotation even if it is not a multiple of 90. Off by default.
	* @param value The new value for UseNonStandardRotation.
	* @return This object, for call chaining.
	*/
	MergeXFDFOptions& SetUseNonStandardRotation(bool value);

	
};

}
}

#include "../Impl/MergeXFDFOptions.inl"
#endif // PDFTRON_H_CPPPDFMergeXFDFOptions
