// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline BarcodeOptions::BarcodeOptions()
	: OptionsBase()
{
}

inline BarcodeOptions::~BarcodeOptions()
{
}


inline UInt32 BarcodeOptions::GetBarcodeOrientations()
{
	SDF::Obj found = m_dict.FindObj("BarcodeOrientations");
	if(found.IsValid())
	{
		return (UInt32)found.GetNumber();
	}
	return 2147483647;
}

inline BarcodeOptions& BarcodeOptions::SetBarcodeOrientations(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "BarcodeOrientations", value);
	return *this;
}


inline BarcodeOptions::BarcodeProfile BarcodeOptions::GetBarcodeProfile()
{
	SDF::Obj found = m_dict.FindObj("BarcodeProfile");
	if(found.IsValid())
	{
		return (BarcodeProfile)(int)(found.GetNumber());
	}
	return (BarcodeProfile)(int)(1);
}

inline BarcodeOptions& BarcodeOptions::SetBarcodeProfile(BarcodeOptions::BarcodeProfile value)
{
	PDF::OptionsBase::PutNumber(m_dict, "BarcodeProfile", (value));
	return *this;
}


inline UInt32 BarcodeOptions::GetBarcodeSearchTypes()
{
	SDF::Obj found = m_dict.FindObj("BarcodeSearchTypes");
	if(found.IsValid())
	{
		return (UInt32)found.GetNumber();
	}
	return 2147483647;
}

inline BarcodeOptions& BarcodeOptions::SetBarcodeSearchTypes(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "BarcodeSearchTypes", value);
	return *this;
}


inline BarcodeOptions::OutputFormat BarcodeOptions::GetDataOutputFormat()
{
	SDF::Obj found = m_dict.FindObj("DataOutputFormat");
	if(found.IsValid())
	{
		return (OutputFormat)(int)(found.GetNumber());
	}
	return (OutputFormat)(int)(0);
}

inline BarcodeOptions& BarcodeOptions::SetDataOutputFormat(BarcodeOptions::OutputFormat value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DataOutputFormat", (value));
	return *this;
}


inline UString BarcodeOptions::GetPages()
{
	SDF::Obj found = m_dict.FindObj("Pages");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline BarcodeOptions& BarcodeOptions::SetPages(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Pages", (value));
	return *this;
}


}
}
