// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline FindReplaceOptions::FindReplaceOptions()
	: OptionsBase()
{
}

inline FindReplaceOptions::~FindReplaceOptions()
{
}


inline FindReplaceOptions::HorizAlignment FindReplaceOptions::GetAlignment()
{
	SDF::Obj found = m_dict.FindObj("Alignment");
	if(found.IsValid())
	{
		return (HorizAlignment)(int)(found.GetNumber());
	}
	return (HorizAlignment)(int)(1);
}

inline FindReplaceOptions& FindReplaceOptions::SetAlignment(FindReplaceOptions::HorizAlignment value)
{
	PDF::OptionsBase::PutNumber(m_dict, "Alignment", (value));
	return *this;
}


inline UInt32 FindReplaceOptions::GetBatchSize()
{
	SDF::Obj found = m_dict.FindObj("BatchSize");
	if(found.IsValid())
	{
		return (UInt32)(found.GetNumber());
	}
	return (UInt32)(20);
}

inline FindReplaceOptions& FindReplaceOptions::SetBatchSize(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "BatchSize", (value));
	return *this;
}


inline bool FindReplaceOptions::GetMatchCase()
{
	SDF::Obj found = m_dict.FindObj("MatchCase");
	if(found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline FindReplaceOptions& FindReplaceOptions::SetMatchCase(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "MatchCase", (value));
	return *this;
}


inline FindReplaceOptions::MatchType FindReplaceOptions::GetMatchMode()
{
	SDF::Obj found = m_dict.FindObj("MatchMode");
	if(found.IsValid())
	{
		return (MatchType)(int)(found.GetNumber());
	}
	return (MatchType)(int)(1);
}

inline FindReplaceOptions& FindReplaceOptions::SetMatchMode(FindReplaceOptions::MatchType value)
{
	PDF::OptionsBase::PutNumber(m_dict, "MatchMode", (value));
	return *this;
}


inline UString FindReplaceOptions::GetPages()
{
	SDF::Obj found = m_dict.FindObj("Pages");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline FindReplaceOptions& FindReplaceOptions::SetPages(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Pages", (value));
	return *this;
}


inline FindReplaceOptions::ReflowType FindReplaceOptions::GetReflowMode()
{
	SDF::Obj found = m_dict.FindObj("ReflowMode");
	if (found.IsValid())
	{
		return (ReflowType)(int)(found.GetNumber());
	}
	return (ReflowType)(int)(3);
}

inline FindReplaceOptions& FindReplaceOptions::SetReflowMode(FindReplaceOptions::ReflowType value)
{
	PDF::OptionsBase::PutNumber(m_dict, "ReflowMode", (value));
	return *this;
}


inline bool FindReplaceOptions::GetWholeWords()
{
	SDF::Obj found = m_dict.FindObj("WholeWords");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline FindReplaceOptions& FindReplaceOptions::SetWholeWords(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "WholeWords", (value));
	return *this;
}


}
}
