//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CTableRow
#define PDFTRON_H_CTableRow


#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>

TRN_API TRN_TableRowAddTableCell(TRN_TableRow self, TRN_TableCell* result);

TRN_API TRN_TableRowSetRowHeight(TRN_TableRow self, double val);
TRN_API TRN_TableRowGetNumColumns(TRN_TableRow self, TRN_UInt32* result);

#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CTableRow */
