//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CStructuredOutputModule
#define PDFTRON_H_CStructuredOutputModule

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_StructuredOutputModule_tag;
typedef struct TRN_StructuredOutputModule_tag* TRN_StructuredOutputModule;


/* methods: */
TRN_API TRN_StructuredOutputModuleIsModuleAvailable(TRN_Bool* result);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CStructuredOutputModule */
