//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CHandwritingICRModule
#define PDFTRON_H_CHandwritingICRModule

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_HandwritingICRModule_tag;
typedef struct TRN_HandwritingICRModule_tag* TRN_HandwritingICRModule;

TRN_API TRN_HandwritingICRModuleIsModuleAvailable(TRN_Bool* result);
TRN_API TRN_HandwritingICRModuleGetICRJsonFromPDF(TRN_PDFDoc src, const TRN_OptionBase* options, TRN_UString* result);
TRN_API TRN_HandwritingICRModuleGetICRJsonFromPDFWithOptsObj(TRN_PDFDoc src, TRN_Obj options, TRN_UString* result);
TRN_API TRN_HandwritingICRModuleApplyICRJsonToPDF(TRN_PDFDoc dst, const TRN_UString json);
TRN_API TRN_HandwritingICRModuleProcessPDF(TRN_PDFDoc dst, const TRN_OptionBase* options);
TRN_API TRN_HandwritingICRModuleProcessPDFWithOptsObj(TRN_PDFDoc dst, TRN_Obj options);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CHandwritingICRModule */
