//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2026 by Apryse Software Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPrintToPdfModule
#define PDFTRON_H_CPrintToPdfModule

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_PrintToPdfModule_tag;
typedef struct TRN_PrintToPdfModule_tag* TRN_PrintToPdfModule;

TRN_API TRN_PrintToPdfModuleIsModuleAvailable(TRN_Bool* result);
TRN_API TRN_PrintToPdfModulePrintToPdf(TRN_PDFDoc pdf_doc, TRN_UString file_to_print, const TRN_OptionBase* options);
TRN_API TRN_PrintToPdfModulePrintToPdfWithOptsObj(TRN_PDFDoc pdf_doc, TRN_UString file_to_print, TRN_Obj options);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CPrintToPdfModule */
