# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'CADViewer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CADViewer
  pod 'PDFNet', podspec: 'https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec'


end
