// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline HandwritingICROptions::HandwritingICROptions()
	: OptionsBase()
{
}

inline HandwritingICROptions::~HandwritingICROptions()
{
}

inline HandwritingICROptions& HandwritingICROptions::AddIgnoreZonesForPage(const RectCollection& value, int page_num)
{
	PDF::OptionsBase::InsertRectCollection(m_dict, "ExclusionZones", value, page_num - 1);
	return *this;
}

inline HandwritingICROptions& HandwritingICROptions::AddInclusionZonesForPage(const RectCollection& value, int page_num)
{
	PDF::OptionsBase::InsertRectCollection(m_dict, "InclusionZones", value, page_num - 1);
	return *this;
}

inline UString HandwritingICROptions::GetPages()
{
	SDF::Obj found = m_dict.FindObj("Pages");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline HandwritingICROptions& HandwritingICROptions::SetPages(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Pages", (value));
	return *this;
}


}
}
