// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline OfficeToPDFOptions::OfficeToPDFOptions()
	: ConversionOptions()
{
}

inline OfficeToPDFOptions::~OfficeToPDFOptions()
{
}


inline OfficeToPDFOptions::AnimationMode OfficeToPDFOptions::GetAnimationHandling()
{
	SDF::Obj found = m_dict.FindObj("AnimationMode");
	if (found.IsValid())
	{
		return (AnimationMode)(int)(found.GetNumber());
	}
	return (AnimationMode)(int)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetAnimationHandling(OfficeToPDFOptions::AnimationMode value)
{
	PDF::OptionsBase::PutNumber(m_dict, "AnimationMode", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetApplyPageBreaksToSheet()
{
	SDF::Obj found = m_dict.FindObj("ApplyPageBreaksToSheet");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetApplyPageBreaksToSheet(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "ApplyPageBreaksToSheet", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultMarginBottom()
{
	SDF::Obj found = m_dict.FindObj("DefaultMarginBottom");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (1.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultMarginBottom(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultMarginBottom", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultMarginLeft()
{
	SDF::Obj found = m_dict.FindObj("DefaultMarginLeft");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (1.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultMarginLeft(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultMarginLeft", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultMarginRight()
{
	SDF::Obj found = m_dict.FindObj("DefaultMarginRight");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (1.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultMarginRight(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultMarginRight", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultMarginTop()
{
	SDF::Obj found = m_dict.FindObj("DefaultMarginTop");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (1.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultMarginTop(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultMarginTop", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultPageHeight()
{
	SDF::Obj found = m_dict.FindObj("DefaultPageHeight");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (11.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultPageHeight(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultPageHeight", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetDefaultPageWidth()
{
	SDF::Obj found = m_dict.FindObj("DefaultPageWidth");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (8.5);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDefaultPageWidth(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DefaultPageWidth", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisableExcelHeadersFooters()
{
	SDF::Obj found = m_dict.FindObj("DisableExcelHeadersFooters");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisableExcelHeadersFooters(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisableExcelHeadersFooters", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisableExcelMargins()
{
	SDF::Obj found = m_dict.FindObj("DisableExcelMargins");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisableExcelMargins(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisableExcelMargins", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisableSheetHeightLimit()
{
	SDF::Obj found = m_dict.FindObj("DisableSheetHeightLimit");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisableSheetHeightLimit(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisableSheetHeightLimit", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisplayChangeTracking()
{
	SDF::Obj found = m_dict.FindObj("DisplayChangeTracking");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (true);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisplayChangeTracking(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisplayChangeTracking", (value));
	return *this;
}


inline OfficeToPDFOptions::DisplayComments OfficeToPDFOptions::GetDisplayComments()
{
	SDF::Obj found = m_dict.FindObj("DisplayComments");
	if (found.IsValid())
	{
		return (DisplayComments)(int)(found.GetNumber());
	}
	return (DisplayComments)(int)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisplayComments(OfficeToPDFOptions::DisplayComments value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DisplayComments", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisplayHiddenCells()
{
	SDF::Obj found = m_dict.FindObj("DisplayHiddenCells");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisplayHiddenCells(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisplayHiddenCells", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetDisplayHiddenText()
{
	SDF::Obj found = m_dict.FindObj("DisplayHiddenText");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisplayHiddenText(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "DisplayHiddenText", (value));
	return *this;
}


inline OfficeToPDFOptions::DisplaySpeakerNotes OfficeToPDFOptions::GetDisplaySpeakerNotes()
{
	SDF::Obj found = m_dict.FindObj("DisplaySpeakerNotes");
	if (found.IsValid())
	{
		return (DisplaySpeakerNotes)(int)(found.GetNumber());
	}
	return (DisplaySpeakerNotes)(int)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetDisplaySpeakerNotes(OfficeToPDFOptions::DisplaySpeakerNotes value)
{
	PDF::OptionsBase::PutNumber(m_dict, "DisplaySpeakerNotes", (value));
	return *this;
}


inline double OfficeToPDFOptions::GetExcelDefaultCellBorderWidth()
{
	SDF::Obj found = m_dict.FindObj("ExcelDefaultCellBorderWidth");
	if (found.IsValid())
	{
		return (found.GetNumber());
	}
	return (0.0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetExcelDefaultCellBorderWidth(double value)
{
	PDF::OptionsBase::PutNumber(m_dict, "ExcelDefaultCellBorderWidth", (value));
	return *this;
}


inline UInt32 OfficeToPDFOptions::GetExcelMaxAllowedCellCount()
{
	SDF::Obj found = m_dict.FindObj("ExcelMaxAllowedCellCount");
	if (found.IsValid())
	{
		return (UInt32)(found.GetNumber());
	}
	return (UInt32)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetExcelMaxAllowedCellCount(UInt32 value)
{
	PDF::OptionsBase::PutNumber(m_dict, "ExcelMaxAllowedCellCount", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetHideTotalNumberOfPages()
{
	SDF::Obj found = m_dict.FindObj("HideTotalNumberOfPages");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetHideTotalNumberOfPages(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "HideTotalNumberOfPages", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetIncludeBookmarks()
{
	SDF::Obj found = m_dict.FindObj("IncludeBookmarks");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (true);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetIncludeBookmarks(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "IncludeBookmarks", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetIncrementalSave()
{
	SDF::Obj found = m_dict.FindObj("IncrementalSave");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetIncrementalSave(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "IncrementalSave", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetLayoutResourcesPluginPath()
{
	SDF::Obj found = m_dict.FindObj("LayoutResourcesPluginPath");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetLayoutResourcesPluginPath(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "LayoutResourcesPluginPath", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetLocale()
{
	SDF::Obj found = m_dict.FindObj("Locale");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetLocale(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Locale", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetPassword()
{
	SDF::Obj found = m_dict.FindObj("Password");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetPassword(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "Password", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetResourceDocPath()
{
	SDF::Obj found = m_dict.FindObj("ResourceDocPath");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetResourceDocPath(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "ResourceDocPath", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetSmartSubstitutionPluginPath()
{
	SDF::Obj found = m_dict.FindObj("SmartSubstitutionPluginPath");
	if(found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetSmartSubstitutionPluginPath(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "SmartSubstitutionPluginPath", (value));
	return *this;
}

inline bool OfficeToPDFOptions::GetShowExcelGridlines()
{
	SDF::Obj found = m_dict.FindObj("ShowExcelGridlines");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetShowExcelGridlines(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "ShowExcelGridlines", (value));
	return *this;
}


inline OfficeToPDFOptions::StructureTagLevel OfficeToPDFOptions::GetStructureTagLevel()
{
	SDF::Obj found = m_dict.FindObj("structure_tag_level");
	if (found.IsValid())
	{
		return (StructureTagLevel)(int)(found.GetNumber());
	}
	return (StructureTagLevel)(int)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetStructureTagLevel(OfficeToPDFOptions::StructureTagLevel value)
{
	PDF::OptionsBase::PutNumber(m_dict, "structure_tag_level", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetTemplateLeftDelimiter()
{
	SDF::Obj found = m_dict.FindObj("TemplateLeftDelimiter");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("{{");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetTemplateLeftDelimiter(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "TemplateLeftDelimiter", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetTemplateParamsJson()
{
	SDF::Obj found = m_dict.FindObj("TemplateParamsJson");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetTemplateParamsJson(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "TemplateParamsJson", (value));
	return *this;
}


inline UString OfficeToPDFOptions::GetTemplateRightDelimiter()
{
	SDF::Obj found = m_dict.FindObj("TemplateRightDelimiter");
	if (found.IsValid())
	{
		return (found.GetAsPDFText());
	}
	return ("}}");
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetTemplateRightDelimiter(const UString& value)
{
	PDF::OptionsBase::PutText(m_dict, "TemplateRightDelimiter", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetTemplateStrictMode()
{
	SDF::Obj found = m_dict.FindObj("TemplateStrictMode");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetTemplateStrictMode(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "TemplateStrictMode", (value));
	return *this;
}


inline OfficeToPDFOptions::UpdateDynamicFields OfficeToPDFOptions::GetUpdateDynamicFields()
{
	SDF::Obj found = m_dict.FindObj("UpdateDynamicFields");
	if (found.IsValid())
	{
		return (UpdateDynamicFields)(int)(found.GetNumber());
	}
	return (UpdateDynamicFields)(int)(0);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetUpdateDynamicFields(OfficeToPDFOptions::UpdateDynamicFields value)
{
	PDF::OptionsBase::PutNumber(m_dict, "UpdateDynamicFields", (value));
	return *this;
}


inline bool OfficeToPDFOptions::GetUpdateTableOfContents()
{
	SDF::Obj found = m_dict.FindObj("UpdateTableOfContents");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline OfficeToPDFOptions& OfficeToPDFOptions::SetUpdateTableOfContents(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "UpdateTableOfContents", (value));
	return *this;
}


}
}
