// This file is autogenerated: please see the codegen template "Options"
namespace pdftron{ namespace PDF{ 

inline SanitizeOptions::SanitizeOptions()
	: OptionsBase()
{
}

inline SanitizeOptions::SanitizeOptions(const UString &json)
	: OptionsBase(json)
{
}

inline SanitizeOptions::~SanitizeOptions()
{
}


inline bool SanitizeOptions::GetActions()
{
	SDF::Obj found = m_dict.FindObj("Actions");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetActions(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "Actions", (value));
	return *this;
}


inline bool SanitizeOptions::GetBookmarks()
{
	SDF::Obj found = m_dict.FindObj("Bookmarks");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetBookmarks(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "Bookmarks", (value));
	return *this;
}


inline bool SanitizeOptions::GetEmbeddedContent()
{
	SDF::Obj found = m_dict.FindObj("EmbeddedContent");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetEmbeddedContent(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "EmbeddedContent", (value));
	return *this;
}


inline bool SanitizeOptions::GetFormData()
{
	SDF::Obj found = m_dict.FindObj("FormData");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetFormData(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "FormData", (value));
	return *this;
}


inline bool SanitizeOptions::GetHiddenLayers()
{
	SDF::Obj found = m_dict.FindObj("HiddenLayers");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetHiddenLayers(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "HiddenLayers", (value));
	return *this;
}


inline bool SanitizeOptions::GetHiddenText()
{
	SDF::Obj found = m_dict.FindObj("HiddenText");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetHiddenText(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "HiddenText", (value));
	return *this;
}


inline bool SanitizeOptions::GetMarkups()
{
	SDF::Obj found = m_dict.FindObj("Markups");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetMarkups(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "Markups", (value));
	return *this;
}


inline bool SanitizeOptions::GetMetadata()
{
	SDF::Obj found = m_dict.FindObj("Metadata");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetMetadata(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "Metadata", (value));
	return *this;
}


inline bool SanitizeOptions::GetOccludedText()
{
	SDF::Obj found = m_dict.FindObj("OccludedText");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetOccludedText(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "OccludedText", (value));
	return *this;
}


inline bool SanitizeOptions::GetSearchIndices()
{
	SDF::Obj found = m_dict.FindObj("SearchIndices");
	if (found.IsValid())
	{
		return (found.GetBool());
	}
	return (false);
}

inline SanitizeOptions& SanitizeOptions::SetSearchIndices(bool value)
{
	PDF::OptionsBase::PutBool(m_dict, "SearchIndices", (value));
	return *this;
}


}
}
