/*#ifndef PDFNetOBJC_Private_H
#define PDFNetOBJC_Private_H*/

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#import <Foundation/Foundation.h>


@interface SWIGTYPE_p_p_TRN_obj_ : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (instancetype)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end


@interface SWIGTYPE_p_pdftron__PDF__TaggingOptions : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
- (void*)getCptr;
- (instancetype)initWithCptr: (void*) cptr;
- (void)setSwigCMemOwn: (BOOL) own;
@end



/*#endif // PDFNetOBJC_Private_H*/

